<?php
namespace Zodream\Http;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-10 at 23:55:40.
 */
use PHPUnit\Framework\TestCase;

class CurlTest extends TestCase {
    /**
     * @var Curl     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Curl;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }
    /**
     * @covers \Zodream\Http\Curl::beforeSend     * @todo   Implement testBeforeSend().
     */
    public function testBeforeSend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::buildPostData     * @todo   Implement testBuildPostData().
     */
    public function testBuildPostData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::call     * @todo   Implement testCall().
     */
    public function testCall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::close     * @todo   Implement testClose().
     */
    public function testClose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::complete     * @todo   Implement testComplete().
     */
    public function testComplete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::progress     * @todo   Implement testProgress().
     */
    public function testProgress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::delete     * @todo   Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::download     * @todo   Implement testDownload().
     */
    public function testDownload() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::error     * @todo   Implement testError().
     */
    public function testError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::exec     * @todo   Implement testExec().
     */
    public function testExec() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::get     * @todo   Implement testGet().
     */
    public function testGet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::getInfo     * @todo   Implement testGetInfo().
     */
    public function testGetInfo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::getOpt     * @todo   Implement testGetOpt().
     */
    public function testGetOpt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::head     * @todo   Implement testHead().
     */
    public function testHead() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::options     * @todo   Implement testOptions().
     */
    public function testOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::patch     * @todo   Implement testPatch().
     */
    public function testPatch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::post     * @todo   Implement testPost().
     */
    public function testPost() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::put     * @todo   Implement testPut().
     */
    public function testPut() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::search     * @todo   Implement testSearch().
     */
    public function testSearch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setBasicAuthentication     * @todo   Implement testSetBasicAuthentication().
     */
    public function testSetBasicAuthentication() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setDigestAuthentication     * @todo   Implement testSetDigestAuthentication().
     */
    public function testSetDigestAuthentication() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setCookie     * @todo   Implement testSetCookie().
     */
    public function testSetCookie() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setCookies     * @todo   Implement testSetCookies().
     */
    public function testSetCookies() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::getCookie     * @todo   Implement testGetCookie().
     */
    public function testGetCookie() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::getResponseCookie     * @todo   Implement testGetResponseCookie().
     */
    public function testGetResponseCookie() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setMaxFilesize     * @todo   Implement testSetMaxFilesize().
     */
    public function testSetMaxFilesize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setPort     * @todo   Implement testSetPort().
     */
    public function testSetPort() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setConnectTimeout     * @todo   Implement testSetConnectTimeout().
     */
    public function testSetConnectTimeout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setCookieString     * @todo   Implement testSetCookieString().
     */
    public function testSetCookieString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setCookieFile     * @todo   Implement testSetCookieFile().
     */
    public function testSetCookieFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setCookieJar     * @todo   Implement testSetCookieJar().
     */
    public function testSetCookieJar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setDefaultJsonDecoder     * @todo   Implement testSetDefaultJsonDecoder().
     */
    public function testSetDefaultJsonDecoder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setDefaultXmlDecoder     * @todo   Implement testSetDefaultXmlDecoder().
     */
    public function testSetDefaultXmlDecoder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setDefaultDecoder     * @todo   Implement testSetDefaultDecoder().
     */
    public function testSetDefaultDecoder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setDefaultTimeout     * @todo   Implement testSetDefaultTimeout().
     */
    public function testSetDefaultTimeout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setDefaultUserAgent     * @todo   Implement testSetDefaultUserAgent().
     */
    public function testSetDefaultUserAgent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setHeader     * @todo   Implement testSetHeader().
     */
    public function testSetHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setHeaders     * @todo   Implement testSetHeaders().
     */
    public function testSetHeaders() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setJsonDecoder     * @todo   Implement testSetJsonDecoder().
     */
    public function testSetJsonDecoder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setXmlDecoder     * @todo   Implement testSetXmlDecoder().
     */
    public function testSetXmlDecoder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setOpt     * @todo   Implement testSetOpt().
     */
    public function testSetOpt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setOpts     * @todo   Implement testSetOpts().
     */
    public function testSetOpts() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setReferer     * @todo   Implement testSetReferer().
     */
    public function testSetReferer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setReferrer     * @todo   Implement testSetReferrer().
     */
    public function testSetReferrer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setTimeout     * @todo   Implement testSetTimeout().
     */
    public function testSetTimeout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setUrl     * @todo   Implement testSetUrl().
     */
    public function testSetUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::setUserAgent     * @todo   Implement testSetUserAgent().
     */
    public function testSetUserAgent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::success     * @todo   Implement testSuccess().
     */
    public function testSuccess() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::unsetHeader     * @todo   Implement testUnsetHeader().
     */
    public function testUnsetHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::removeHeader     * @todo   Implement testRemoveHeader().
     */
    public function testRemoveHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::verbose     * @todo   Implement testVerbose().
     */
    public function testVerbose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::__destruct     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Curl::__get     * @todo   Implement test__get().
     */
    public function test__get() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
