<?php
namespace Zodream\Http;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-10 at 23:55:40.
 */
use PHPUnit\Framework\TestCase;

class MultiCurlTest extends TestCase {
    /**
     * @var MultiCurl     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MultiCurl;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }
    /**
     * @covers \Zodream\Http\MultiCurl::addDelete     * @todo   Implement testAddDelete().
     */
    public function testAddDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::addDownload     * @todo   Implement testAddDownload().
     */
    public function testAddDownload() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::addGet     * @todo   Implement testAddGet().
     */
    public function testAddGet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::addHead     * @todo   Implement testAddHead().
     */
    public function testAddHead() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::addOptions     * @todo   Implement testAddOptions().
     */
    public function testAddOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::addPatch     * @todo   Implement testAddPatch().
     */
    public function testAddPatch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::addPost     * @todo   Implement testAddPost().
     */
    public function testAddPost() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::addPut     * @todo   Implement testAddPut().
     */
    public function testAddPut() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::addSearch     * @todo   Implement testAddSearch().
     */
    public function testAddSearch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::addCurl     * @todo   Implement testAddCurl().
     */
    public function testAddCurl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::beforeSend     * @todo   Implement testBeforeSend().
     */
    public function testBeforeSend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::close     * @todo   Implement testClose().
     */
    public function testClose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::complete     * @todo   Implement testComplete().
     */
    public function testComplete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::error     * @todo   Implement testError().
     */
    public function testError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::getOpt     * @todo   Implement testGetOpt().
     */
    public function testGetOpt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setBasicAuthentication     * @todo   Implement testSetBasicAuthentication().
     */
    public function testSetBasicAuthentication() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setConcurrency     * @todo   Implement testSetConcurrency().
     */
    public function testSetConcurrency() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setDigestAuthentication     * @todo   Implement testSetDigestAuthentication().
     */
    public function testSetDigestAuthentication() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setCookie     * @todo   Implement testSetCookie().
     */
    public function testSetCookie() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setCookies     * @todo   Implement testSetCookies().
     */
    public function testSetCookies() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setPort     * @todo   Implement testSetPort().
     */
    public function testSetPort() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setConnectTimeout     * @todo   Implement testSetConnectTimeout().
     */
    public function testSetConnectTimeout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setCookieString     * @todo   Implement testSetCookieString().
     */
    public function testSetCookieString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setCookieFile     * @todo   Implement testSetCookieFile().
     */
    public function testSetCookieFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setCookieJar     * @todo   Implement testSetCookieJar().
     */
    public function testSetCookieJar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setHeader     * @todo   Implement testSetHeader().
     */
    public function testSetHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setHeaders     * @todo   Implement testSetHeaders().
     */
    public function testSetHeaders() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setJsonDecoder     * @todo   Implement testSetJsonDecoder().
     */
    public function testSetJsonDecoder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setXmlDecoder     * @todo   Implement testSetXmlDecoder().
     */
    public function testSetXmlDecoder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setOpt     * @todo   Implement testSetOpt().
     */
    public function testSetOpt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setOpts     * @todo   Implement testSetOpts().
     */
    public function testSetOpts() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setReferer     * @todo   Implement testSetReferer().
     */
    public function testSetReferer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setReferrer     * @todo   Implement testSetReferrer().
     */
    public function testSetReferrer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setTimeout     * @todo   Implement testSetTimeout().
     */
    public function testSetTimeout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setUrl     * @todo   Implement testSetUrl().
     */
    public function testSetUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::setUserAgent     * @todo   Implement testSetUserAgent().
     */
    public function testSetUserAgent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::start     * @todo   Implement testStart().
     */
    public function testStart() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::success     * @todo   Implement testSuccess().
     */
    public function testSuccess() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::unsetHeader     * @todo   Implement testUnsetHeader().
     */
    public function testUnsetHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::removeHeader     * @todo   Implement testRemoveHeader().
     */
    public function testRemoveHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::verbose     * @todo   Implement testVerbose().
     */
    public function testVerbose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\MultiCurl::__destruct     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
