<?php
namespace Zodream\Http;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-10 at 23:55:40.
 */
use PHPUnit\Framework\TestCase;

class SocketTest extends TestCase {
    /**
     * @var Socket     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Socket;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }
    /**
     * @covers \Zodream\Http\Socket::setIpAddress     * @todo   Implement testSetIpAddress().
     */
    public function testSetIpAddress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Socket::create     * @todo   Implement testCreate().
     */
    public function testCreate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Socket::listen     * @todo   Implement testListen().
     */
    public function testListen() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Socket::connect     * @todo   Implement testConnect().
     */
    public function testConnect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Socket::accept     * @todo   Implement testAccept().
     */
    public function testAccept() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Socket::read     * @todo   Implement testRead().
     */
    public function testRead() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Socket::write     * @todo   Implement testWrite().
     */
    public function testWrite() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Socket::close     * @todo   Implement testClose().
     */
    public function testClose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
/**
     * @covers \Zodream\Http\Socket::getError     * @todo   Implement testGetError().
     */
    public function testGetError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
